### ISSUE TITLE
Broken Dverger Circlet

### ISSUE THREAD

**Issue by NeonCarbide** [NeonCarbide/Valheim-NeonPack#2]
Due to the functionality of Invis Helm that allows the ability to use a Dverger Circlet for light at the same time as wearing a normal helm for armour, equipping and unequipping the items could cause the Dverger Circlet to break completely until a relog is performed.

Will remove Invis Helm in the next modpack update and add it back in when this issue has been solved

**Comment by NeonCarbide** [comment]
Fixed in 1.10.1 update

**Comment by SpudTatterson** [comment]
hi this is the creator of invishelm could u tell me how to recreate the issue u are talking about?

**Comment by NeonCarbide** [comment]
> hi this is the creator of invishelm could u tell me how to recreate the issue u are talking about?

The most noticeable form of this bug is obtained by doing the following:

- Starting with no head slot items equipped, right-click equip helmet
- Right-click equip Dverger Circlet without removing helmet
- Right-click equip helmet without removing Dverger Circlet
- Toggle visibility of helmet with hotkey

Upon toggling helmet visibility via hotkey, the light from the Dverger Circlet disappears and will not reappear, even if the circlet is re-equipped, until the player at least logs out to the main menu

Just to make you aware, I am also using ImprovedDvergerCirclet 1.0.1 and EquipmentAndQuickSlots 2.0.2, both mods by RandyKnapp
